<?php
const SESSION_USERID = 'userID';
const SESSION_MAIL = 'userEmail';
const REMEMBER_ME_COOKIE_EXPIRY = 2592000;
const REMEMBER_ME_COOKIE_NAME = 'rememberMe';
const SESSION_PRIVILEGE = 'Standard';
const ADMIN = 'Admin';

const DATABASE_SERVER_NAME = 'localhost';
const DATABASE_USER_NAME = 'root';
const DATABASE_PASSWORD = '';
const DATABASE_NAME = '9.0';

const INVALID_UPLOAD = 'INVALID_UPLOAD';
const EMPTY_FIELDS = 'EMPTY_FIELDS';
const INVALID_USERNAME = 'INVALID_USERNAME';
const INVALID_MAIL = 'INVALID_EMAIL';
const INVALID_PASSWORD_MATCH = 'INVALID_PASSWORD_MATCH';
const EMAIL_TAKEN = 'EMAIL_TAKEN';
const USERNAME_TAKEN = 'USERNAME_TAKEN';

const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
const INVALID_PROJECT_LINK = 'INVALID_PROJECT_LINK';
const INVALID_PROJECT_NAME = 'INVALID_PROJECT_NAME';
const INVALID_FIRST_NAME = 'INVALID_FIRST_NAME';
const INVALID_PROJECT_DESCRIPTION = 'INVALID_PROJECT_DESCRIPTION';
const INVALID_LAST_NAME = 'INVALID_LAST_NAME';
const INVALID_PASSWORD = 'INVALID_PASSWORD';
const INVALID_IMAGE = 'INVALID_IMAGE';

const INVALID_TITLE = 'INVALID_TITLE';
const INVALID_TOPIC = 'INVALID_TOPIC';
const INVALID_TEXT = 'INVALID_TEXT';

//Courses
const INVALID_CREDITS = 'INVALID_CREDITS';

//User
const INVALID_DESCRIPTION = 'INVALID_DESCRIPTION';
const INVALID_EMAIL = 'INVALID_EMAIL';

//Degrees
const INVALID_NAME = "INVALID_NAME";
const INVALID_COUNTRY = "INVALID_COUNTRY";
const INVALID_CITY = "INVALID_CITY";
const INVALID_UNIVERSITY = "INVALID_UNIVERSITY";
const INVALID_FIELD_OF_STUDY = "INVALID_FIELD_OF_STUDY";
const INVALID_DATES = 'INVALID_DATES';

//Reviews
const INVALID_RATING = "INVALID_RATING";
const INVALID_REVIEW_TEXT = "INVALID_REVIEW_TEXT";

const IMAGE_UPLOAD_WIDTH = 300;
const IMAGE_UPLOAD_HEIGHT = 300;
